### ISSUE TITLE
Generate a page for a release checklist

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/release-droid#181] opened 2021-08-09 14:03 UTC
We want to generate a text page that can be copied directly to the release checklist removing part of manual actions there.

**Comment by ckunki** [comment] 2023-02-07 09:40
Maybe the Release guide implemented in the scope of #275 contains some parts that can be reused?

**Comment by redcatbear** [comment] 2023-11-22 09:53
Duplicate of #275.

**Closed by redcatbear** 2023-11-22 09:53 UTC
Labels: feature
